server:
  port: 8886
spring:
  application:
    name: config
  profiles:
    active: @profileActive@
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhang6317/st-platform.git #配置git仓库地址
          searchPaths: 'config/src/main/config/{profile}' #配置仓库路径
          username:
          password:
      label: master #配置仓库的分支
      profile: ${spring.profiles}
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhang6317/st-platform.git #配置git仓库地址
          searchPaths: 'config/src/main/config/{profile}' #配置仓库路径
          username:
          password:
      label: master #配置仓库的分支
eureka:
    instance:
      hostname: ${spring.cloud.client.ip-address}
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
      serviceUrl:
        defaultZone: http://172.17.0.1:8761/eureka/